markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 铃儿响叮当
host: binli.github.com
desc: BinLi's blog

custom:
    category:
        worklog: day-to-day
        community: Community
        kernel: Kernel
        uncategorized: Uncategorized
    categories:
      - name:  worklog
        title: day-to-day

      - name:  community
        title: Community

      - name:  kernel
        title: Kernel

      - name:  uncategorized
        title: Uncategorized

meta:
    author:
        name: Bin Li
        email: binli@opensuse.org
        disqus: binli                               # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: binli                               # GitHub账号
        gravatar: f1a607bf4fe0dd69bc8cff260e387735  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
