baseURL = "http://binli.github.io/"
title = "Debugging"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

paginate = 30

[markup.highlight]
style = "github-dark"

[params]
author = "Bin Li"

description = "Bin Li's personal website"
keywords = "blog,developer,Linux,GNOME"
info = ["Software Engineer", "Linux & GNOME fans"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
#favicon_32 = "/img/favicon-32x32.png"
#favicon_16 = "/img/favicon-16x16.png"
since = 2013
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/binli/binli40.github.com/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# https://forkaweso.me/Fork-Awesome/icons/
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/binli/"

[[params.social]]
name = "Ubuntu"
icon = "fa fa-2x fa-life-ring"
weight = 2
url = "https://launchpad.net/~binli"

[[params.social]]
name = "GNOME"
icon = "fa fa-2x fa-gimp"
weight = 3
url = "https://gitlab.gnome.org/binli"

[[params.social]]
name = "FreeDesktop"
icon = "fa fa-2x fa-gitlab"
weight = 4
url = "https://gitlab.freedesktop.org/binli"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 5
url = "https://twitter.com/isone/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[languages.cn]
languageName = ":cn:"
title = "填坑老哥"

[languages.cn.params]
author = "Li Bin"
info = ["软件工程师","Linux 和 GNOME 爱好者"]
description = "Li Bin 的个人小站"
keywords = "博客,开发者,Linux系统,GNOME桌面"

[[languages.cn.menu.main]]
name = "关于"
weight = 1
url = "about/"

[[languages.cn.menu.main]]
name = "日志"
weight = 2
url = "posts/"
